### PR TITLE
- Adding key 'LICENSE' to the Makefile.PL script.

### PR DESCRIPTION
**Pull request by Manwar**
Hi Salvador, please review the above change.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by salva** [comment]
Well, it should say `perl_5`!

**Comment by Manwar** [comment]
You just say "perl" and the generated META file will have it "perl_5".

**Comment by salva** [comment]
I have added the entry myself.

**Comment by salva** [comment]
Ummm, it seems EU::MM handles that and if doesn't matter if you put `perl` or `perl_5` because META.yml would say `perl` and META.json `perl_5` in both cases.

Anyway, I prefer to state the specific version in the source.

**Pull request closed without merging**
